create table if not exists public.favourite_jams (
  id bigint generated by default as identity primary key,
  clerk_user_id text not null,
  jam_session_id bigint not null references public.jam_sessions(id) on delete cascade,
  created_at timestamptz not null default now(),
  unique (clerk_user_id, jam_session_id)
);

create index if not exists favourite_jams_clerk_user_id_idx
  on public.favourite_jams (clerk_user_id);

create index if not exists favourite_jams_jam_session_id_idx
  on public.favourite_jams (jam_session_id);

alter table public.favourite_jams enable row level security;

revoke all on table public.favourite_jams from anon;
revoke all on table public.favourite_jams from authenticated;
