create table if not exists public.jam_sessions (
  id bigint generated by default as identity primary key,
  genre text not null,
  name text not null,
  description text,
  event_date text not null,
  event_time text not null,
  location text not null,
  frequency text not null,
  image_url text not null,
  created_at timestamptz not null default now()
);

alter table public.jam_sessions enable row level security;

create policy "Allow public read access to jam sessions"
on public.jam_sessions
for select
using (true);

insert into public.jam_sessions (genre, name, event_date, event_time, location, frequency, image_url)
values
  (
    'Jazz',
    'Harbour Swing Circle',
    'Wednesday, April 22, 2026',
    '7:30 PM',
    'The Lantern Room, Newtown, Sydney',
    'Weekly',
    'https://images.unsplash.com/photo-1511192336575-5a79af67a629?auto=format&fit=crop&w=1200&q=80'
  ),
  (
    'Bluegrass',
    'Southern Cross Pickers',
    'Friday, April 24, 2026',
    '6:30 PM',
    'Stringlight Hall, Surry Hills, Sydney',
    'Monthly',
    'https://images.unsplash.com/photo-1511379938547-c1f69419868d?auto=format&fit=crop&w=1200&q=80'
  ),
  (
    'Folk',
    'Darlinghurst Folk Fire',
    'Sunday, April 26, 2026',
    '5:00 PM',
    'Willow Courtyard, Darlinghurst, Sydney',
    'Weekly',
    'https://images.unsplash.com/photo-1501386761578-eac5c94b800a?auto=format&fit=crop&w=1200&q=80'
  ),
  (
    'Blues',
    'Midnight Wharf Blues Jam',
    'Saturday, May 2, 2026',
    '8:00 PM',
    'Brickhouse Cellar, Pyrmont, Sydney',
    'Monthly',
    'https://images.unsplash.com/photo-1460723237483-7a6dc9d0b212?auto=format&fit=crop&w=1200&q=80'
  ),
  (
    'Fusion',
    'Metro Pulse Collective',
    'Thursday, April 30, 2026',
    '7:00 PM',
    'Echo Studio Loft, Chippendale, Sydney',
    'Weekly',
    'https://images.unsplash.com/photo-1493225457124-a3eb161ffa5f?auto=format&fit=crop&w=1200&q=80'
  );

alter table public.jam_sessions
add column if not exists description text;

update public.jam_sessions
set description = case name
  when 'Harbour Swing Circle' then 'A relaxed midweek jazz hang with walking bass, brushed drums, and open solos. Best for players who enjoy standards, quick call-outs, and a friendly rotating house trio.'
  when 'Southern Cross Pickers' then 'An acoustic bluegrass session centered on tight vocal harmonies, fiddle tunes, and fast flatpicking breaks. Bring a mandolin, banjo, guitar, or upright bass for round-robin sets.'
  when 'Darlinghurst Folk Fire' then 'An early-evening folk circle with storyteller songs, warm harmonies, and light percussion. Expect sing-alongs, original tunes, and a welcoming all-levels atmosphere in an outdoor courtyard.'
  when 'Midnight Wharf Blues Jam' then 'A late-night electric blues jam with gritty riffs, slow burners, and shuffle grooves. Backline support and a host band keep the set flowing for guitarists, harp players, and vocalists.'
  when 'Metro Pulse Collective' then 'A genre-bending fusion night blending funk rhythm sections, jazz harmony, and modern electronic textures. Great for adventurous improvisers who like odd meters and dynamic group interplay.'
  else description
end
where description is null;
